<a href="https://www.kaggle.com/code/avikdas567/exercise-getting-started-with-sql-and-bigquery?scriptVersionId=277628547" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [1]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

/usr/local/lib/python3.11/dist-packages/learntools/sql/ex1.py:64: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (type(fields_for_plotting[0] == str), "The first item in `fields_for_plotting` should be a string.")
/usr/local/lib/python3.11/dist-packages/learntools/sql/ex1.py:65: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (type(fields_for_plotting[1] == str), "The second item in `fields_for_plotting` should be a string.")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

Use the next code cell to fetch the dataset.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [3]:
# List all the tables in the "chicago_crime" Dataset
tables = list(client.list_tables(dataset))

# Print names of all tables in the dataset
for table in tables:
    print(table.table_id)

crime

In [4]:
num_tables = len(tables)
print(f"Number of tables in the 'chicago_crime' dataset = {num_tables}")

# Check your answer
q_1.check()

Number of tables in the 'chicago_crime' dataset = 1

Correct

For a hint or the solution, uncomment the appropriate line below.

In [5]:
q_1.hint()
q_1.solution()

Hint: Use the `list_tables()` method to get a list of the tables in the dataset.

Solution:
```python

# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

# Print number of tables in the dataset
print(len(tables))

num_tables = 1

```

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [6]:
# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

In [7]:
# Print information on all the columns in the "crime" table in the "chicago_crime" dataset
table.schema

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', None, None, (), None),
 SchemaField('case_number', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, None, (), None),
 SchemaField('block', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('iucr', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('primary_type', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('description', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('location_description', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('arrest', 'BOOLEAN', 'NULLABLE', None, None, (), None),
 SchemaField('domestic', 'BOOLEAN', 'NULLABLE', None, None, (), None),
 SchemaField('beat', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('district', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('ward', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('community_area', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('fbi_code', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('year', 'INTEGER', 'NULLABLE', None, None, (), None),
 SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', None, None, (), None),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', None, None, (), None),
 SchemaField('location', 'STRING', 'NULLABLE', None, None, (), None)]

In [8]:
num_timestamp_fields = 2

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [9]:
q_2.hint()
q_2.solution()

Hint: Begin by fetching the `crime` table. Then take a look at the table schema, and check the field type of each column.  How many times does `'TIMESTAMP'` appear?

Solution:
```python

# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

# Print information on all the columns in the "crime" table in the "chicago_crime" dataset
print(table.schema)

num_timestamp_fields = 2

```

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [10]:
# Preview the first 5 lines of the "crime" table
client.list_rows(table, max_results=5).to_dataframe()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,11131982,JA487624,2017-10-26 22:00:00+00:00,002XX N DEARBORN ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,...,42,32,02,1175901.0,1901839.0,2017,2018-02-10 15:50:01+00:00,41.886013,-87.629505,"(41.886012928, -87.629505318)"
1,11617733,JC177893,2018-03-01 09:00:00+00:00,001XX N MICHIGAN AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,COMMERCIAL / BUSINESS OFFICE,False,False,...,42,32,02,NaN,NaN,2018,2019-03-10 16:00:57+00:00,NaN,NaN,None
2,7079044,HR486924,2009-08-15 18:30:00+00:00,005XX W MADISON ST,0312,ROBBERY,ARMED:KNIFE/CUTTING INSTRUMENT,STREET,False,False,...,42,28,03,1173039.0,1900311.0,2009,2018-02-10 15:50:01+00:00,41.881884,-87.640060,"(41.881883933, -87.640060441)"
3,6755336,HR172212,2009-02-15 22:20:00+00:00,002XX S CANAL ST,031A,ROBBERY,ARMED: HANDGUN,STREET,False,False,...,2,28,03,1173177.0,1899236.0,2009,2018-02-28 15:56:25+00:00,41.878931,-87.639586,"(41.878931004, -87.639585621)"
4,10357934,HY548907,2015-12-24 12:50:00+00:00,001XX N MICHIGAN AVE,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,False,False,...,42,32,03,1177276.0,1901405.0,2015,2018-02-10 15:50:01+00:00,41.884791,-87.624469,"(41.884790951, -87.624469241)"

In [11]:
fields_for_plotting = ["latitude", "longitude"]

# Check your answer
q_3.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [12]:
q_3.hint()
q_3.solution()

Hint: Look at the table schema.  There are a couple options, but two of the fields are things commonly used to plot on maps. Both are `'FLOAT'` types. Use quotes around the field names in your answer.

Solution:
```python
fields_for_plotting = ['latitude', 'longitude']
```

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [13]:
# Preview the first 10 lines of the "crime" table
client.list_rows(table, max_results=10).to_dataframe()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,11131982,JA487624,2017-10-26 22:00:00+00:00,002XX N DEARBORN ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,...,42,32,02,1175901.0,1901839.0,2017,2018-02-10 15:50:01+00:00,41.886013,-87.629505,"(41.886012928, -87.629505318)"
1,11617733,JC177893,2018-03-01 09:00:00+00:00,001XX N MICHIGAN AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,COMMERCIAL / BUSINESS OFFICE,False,False,...,42,32,02,NaN,NaN,2018,2019-03-10 16:00:57+00:00,NaN,NaN,None
2,7079044,HR486924,2009-08-15 18:30:00+00:00,005XX W MADISON ST,0312,ROBBERY,ARMED:KNIFE/CUTTING INSTRUMENT,STREET,False,False,...,42,28,03,1173039.0,1900311.0,2009,2018-02-10 15:50:01+00:00,41.881884,-87.640060,"(41.881883933, -87.640060441)"
3,6755336,HR172212,2009-02-15 22:20:00+00:00,002XX S CANAL ST,031A,ROBBERY,ARMED: HANDGUN,STREET,False,False,...,2,28,03,1173177.0,1899236.0,2009,2018-02-28 15:56:25+00:00,41.878931,-87.639586,"(41.878931004, -87.639585621)"
4,10357934,HY548907,2015-12-24 12:50:00+00:00,001XX N MICHIGAN AVE,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,False,False,...,42,32,03,1177276.0,1901405.0,2015,2018-02-10 15:50:01+00:00,41.884791,-87.624469,"(41.884790951, -87.624469241)"
5,7017956,HR424795,2009-07-12 11:25:00+00:00,003XX S CANAL ST,0320,ROBBERY,STRONGARM - NO WEAPON,SIDEWALK,False,False,...,2,28,03,1173192.0,1898687.0,2009,2018-02-28 15:56:25+00:00,41.877424,-87.639547,"(41.877424179, -87.639546839)"
6,9733047,HX382996,2014-08-11 12:05:00+00:00,002XX N STATE ST,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,True,False,...,42,32,03,1176327.0,1901797.0,2014,2018-02-10 15:50:01+00:00,41.885888,-87.627942,"(41.885888079, -87.627942238)"
7,3400648,HK449706,2004-06-23 00:30:00+00:00,0000X S CANAL ST,0320,ROBBERY,STRONGARM - NO WEAPON,OTHER,False,False,...,2,28,03,1173143.0,1900251.0,2004,2018-02-28 15:56:25+00:00,41.881717,-87.639680,"(41.881716983, -87.639680339)"
8,4584324,HM175184,2006-02-11 06:25:00+00:00,001XX N FRANKLIN ST,0330,ROBBERY,AGGRAVATED,SMALL RETAIL STORE,False,False,...,42,32,03,1174297.0,1901591.0,2006,2018-02-28 15:56:25+00:00,41.885368,-87.635403,"(41.885368351, -87.635402906)"
9,3612209,HK705839,2004-10-23 20:36:02+00:00,0000X S CLINTON ST,0330,ROBBERY,AGGRAVATED,STREET,False,False,...,2,28,03,1172732.0,1900240.0,2004,2018-02-28 15:56:25+00:00,41.881696,-87.641190,"(41.881695904, -87.641189833)"

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*